project:
  type: book
  output-dir: docs

book:
  title: "Advanced Time-Series and Spatial Analysis in Agriculture with R"
  author: "Johanie Fournier, agr."
  date: "`r format(Sys.time(), '%Y-%m-%d')`"
  chapters:
    - index.qmd
    - "01_introduction.qmd"
    - "02_programming.qmd"
    - "03_multivariate.qmd"
    - "04_non_linear.qmd"
    - "05_ml.qmd"
    - "06_integrating.qmd"
    - "07_forecasting.qmd"
    - "08_computing.qmd"
    - "09_visualization.qmd"
    - "10_analytics.qmd"
    - "11_future.qmd"
    - "12_conclusion.qmd"   
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



