project:
  type: book
  output-dir: docs

book:
  title: "Tidying Spatial Data for Agriculture Usage Purposes"
  author: "Johanie Fournier, agr."
  date: "2024-01-05"
  chapters:
    - index.qmd
    - "01_introduction.qmd"
    - "02_spatial_data_handling.qmd"
    - "03_spatial_data_preprocessing.qmd"
    - "04_spatial_data_visualisation.qmd"
    - "05_spatial_data_eda.qmd"
    - "06_spatial_data_autocorrelation.qmd"
    - "07_spatial_data_interpolation.qmd"
    - "08_spatial_data_modeling.qmd"
    - "09_spatial_data_simulation.qmd"
    - "10_spatial_data_uncertainty.qmd"
    - "11_spatial_data_change_detection.qmd"
    - "12_spatial_data_risk_assessement.qmd"
    - "13_spatial_data_simulation_methods.qmd"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



