project:
  type: book
  output-dir: docs

book:
  title: "Tidying Spatial Data for Agriculture Usage Purposes"
  author: "Johanie Fournier, agr."
  date: "2024-01-05"
  chapters:
    - index.qmd
    - "01_introduction.qmd"
    - "02_spatial_data_handling.qmd"
    - "03_spatial_data_preprocessing.qmd"
    - "04_spatial_data_visualisation.qmd"
    - "05_spatial_data_eda.qmd"
    - "06_spatial_data_modeling.qmd"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



